// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package v1

// Defines values for CategoryType.
const (
	Culinary  CategoryType = "culinary"
	Exotic    CategoryType = "exotic"
	Medicinal CategoryType = "medicinal"
)

// Defines values for ResourceType.
const (
	Items ResourceType = "items"
)

// Defines values for UnitType.
const (
	Count    UnitType = "count"
	Gram     UnitType = "gram"
	Kilogram UnitType = "kilogram"
)

// CategoryType defines model for CategoryType.
type CategoryType string

// CommoditiesItem defines model for CommoditiesItem.
type CommoditiesItem struct {
	Category    CategoryType `json:"category"`
	Description string       `json:"description"`
	Name        string       `json:"name"`
	Price       float32      `json:"price"`
	Quantity    float32      `json:"quantity"`

	// Sku Stock keeping unit is the unit of measure in which the stocks of a material are managed.
	Sku  string   `json:"sku"`
	Unit UnitType `json:"unit"`
}

// Error defines model for Error.
type Error struct {
	// Detail A human-readable explanation specific to this occurrence of the problem
	Detail string `json:"detail"`

	// Id Id of a request
	Id   string `json:"id"`
	Meta struct {
		// Timestamp Timestamp of the occurrence of the problem in RFC3339 format
		Timestamp string `json:"timestamp"`
	} `json:"meta"`

	// Status The HTTP status code applicable to this problem, expressed as a string value
	Status string `json:"status"`
}

// GetCommoditiesResponse defines model for GetCommoditiesResponse.
type GetCommoditiesResponse struct {
	Data []struct {
		Attributes []CommoditiesItem `json:"attributes"`

		// Id Identifier of a commodity
		Id string `json:"id"`

		// Type Available JSON:API resource types
		Type ResourceType `json:"type"`
	} `json:"data"`
}

// ResourceType Available JSON:API resource types
type ResourceType string

// UnitType defines model for UnitType.
type UnitType string
