// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package v1

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CategoryType.
const (
	CategoryTypeCulinary  CategoryType = "culinary"
	CategoryTypeExotic    CategoryType = "exotic"
	CategoryTypeMedicinal CategoryType = "medicinal"
)

// Defines values for UnitType.
const (
	Gram     UnitType = "gram"
	Kilogram UnitType = "kilogram"
)

// Defines values for PaginationLimit.
const (
	PaginationLimitDefault PaginationLimit = 20
	PaginationLimitMax     PaginationLimit = 50
	PaginationLimitMin     PaginationLimit = 1
)

// Defines values for GetProductsParamsCategory.
const (
	GetProductsParamsCategoryCulinary  GetProductsParamsCategory = "culinary"
	GetProductsParamsCategoryExotic    GetProductsParamsCategory = "exotic"
	GetProductsParamsCategoryMedicinal GetProductsParamsCategory = "medicinal"
)

// Defines values for GetProductsParamsLimit.
const (
	GetProductsParamsLimitDefault GetProductsParamsLimit = 20
	GetProductsParamsLimitMax     GetProductsParamsLimit = 50
	GetProductsParamsLimitMin     GetProductsParamsLimit = 1
)

// CategoryType defines model for CategoryType.
type CategoryType string

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	Limit int `json:"limit"`
	Page  int `json:"page"`
	Total int `json:"total"`
}

// ProductItem defines model for ProductItem.
type ProductItem struct {
	Category    CategoryType       `json:"category"`
	CreatedAt   time.Time          `json:"createdAt"`
	Description string             `json:"description"`
	Id          openapi_types.UUID `json:"id"`
	InStock     bool               `json:"inStock"`
	Name        string             `json:"name"`
	Price       float32            `json:"price"`
	Quantity    int                `json:"quantity"`
	Unit        UnitType           `json:"unit"`
}

// UnitType defines model for UnitType.
type UnitType string

// PaginationLimit defines model for PaginationLimit.
type PaginationLimit int

// PaginationPage defines model for PaginationPage.
type PaginationPage = int

// GetProductsParams defines parameters for GetProducts.
type GetProductsParams struct {
	Category    *GetProductsParamsCategory `form:"category,omitempty" json:"category,omitempty"`
	InStockOnly *bool                      `form:"inStockOnly,omitempty" json:"inStockOnly,omitempty"`
	Page        *PaginationPage            `form:"page,omitempty" json:"page,omitempty"`
	Limit       *GetProductsParamsLimit    `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetProductsParamsCategory defines parameters for GetProducts.
type GetProductsParamsCategory string

// GetProductsParamsLimit defines parameters for GetProducts.
type GetProductsParamsLimit int
